### ISSUE TITLE
Usage with SAMSEG (T1 and FLAIR) and correlation with ventricular volume

### ISSUE THREAD

**Issue by robbwh** [EhsanTadayon/choroid-plexus-segmentation#1]
Hello, 

No need to look into this at all, but this may be of interest to you. 

I've been playing around with choroid plexus segmentation using SAMSEG which accepts T1w and FLAIR images. 

Samseg choroid plexus segmentation looks like it does a much better job than ASEG, but in many of our images the choroid plexus is hardly visible on T1w images. Using your tool to improve the ASEG images doesn't seem to help much (as the CP is often barely visible on T1 anyway) and the mixture model doesn't converge. 

While the SAMSEG segmentation seems to do a pretty good job of segmenting the choroid plexus, the choroid plexus volume correlation with lateral ventricle volume is (possibly artifactually) high, with r=0.95. I think you observed r=~0.67 using freesurfer in one of your papers. 

Anyway I'm probably going to try to modify your script to accept the Samseg segmentation and FLAIR images and see if it cleans it up at all.

**Comment by EhsanTadayon** [comment]
Hi, 

sorry for late reply. I have not checked this repository for a long time. Thanks for your suggestions. FLAIR images is not something that a lot of research protocols acquire unfortunately but I agree combining two different modalities will probably do a better job. Please keep us posted if you were able to come up with a new segmentation algorithm.

**Comment by robbwh** [comment]
Hi, 

I never got it to the point where I was satisfied with the output, but if I recall it seemed to do better when I used a samseg segmentation created from both T1 and T2-FLAIR. The T2-FLAIR I was using was 2D and had pretty thick slices so that limited things though. 

Thanks for getting back to me and feel free to close this!
